name: Cosmetics
version: '1.0-DEV'
description: "The cosmetics plugin for Minebo."
authors: ["Ian Rich"]
website: "https://github.com/MineboMC/Lobby"
main: net.minebo.cosmetics.Cosmetics
api-version: '1.20'